### PR TITLE
ghc 8.4.3 support

### PR DESCRIPTION
**Pull request by Lupino**
* instance super class Semigroup for lts-12.2

### CODE REVIEW

**Comment by Nate-Bragg-Bose** [comment]
Thanks for the PR.  Our LTS is quite old, so maybe it's about time to upgrade.  I'm a little hesitant to jump all the way to the bleeding edge, though---is there something significant about GHC 8.4.3, or would 8.2.2 (LTS 10.10 or 11.18) be okay?

Either way, could you make the Graphviz Semigroup instances use `(<>)` instead of `mappend`, as you did for the rest?  Also, could you fix the warnings raised by Travis and AppVeyor, since I'd like to keep the build warning-free?  They can be solved by rewriting lines 43-45 inside a block using `withExeLBI`.

**Comment by Nate-Bragg-Bose** [comment]
@Lupino I'd like to move forward with this, but do you have any comment about the LTS version?

Also, any idea about the custom build failure?  It seems to be random.  I'm really hesitant to merge if the build will start randomly failing.

**Comment by Lupino** [comment]
I don't know why it build failed on windows.   on my macos is ok and linux is also OK.

**Comment by Nate-Bragg-Bose** [comment]
It appears the issue with the AppVeyor build is caused by a change in how Cabal handles paths, which is broken for some packages (whose maintainers presumably don't run Windows).  For more detail, see [this blog post](https://www.fpcomplete.com/blog/2018/06/sed-a-debugging-story).

I'll accept this, but if you would like to keep contributing, please know that the Windows build is a primary target for Smudge, and it's what most of our users run.

**Comment by Nate-Bragg-Bose** [comment]
As an update, I could not get this passing for LTS 12, so I have undone chunks of this PR, and pushed it back to LTS 10.10, which is where we will stay for the foreseeable future.  I hope that's not a problem for whatever originally inspired this pull request.

**Pull request merged**
